<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>TemplateFrame.Demo</RootNamespace>
    <AssemblyName>TemplateFrame.Demo</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TemplateFrame\TemplateFrame.csproj" />
    <ProjectReference Include="..\..\src\TemplateFrame.Word\TemplateFrame.Word.csproj" />
  </ItemGroup>

</Project>
